"""Course-specific flashcards generator."""

from typing import Dict, List, Any
from app.simple_models import DifficultyLevel


# Course-specific flashcards mapping
COURSE_FLASHCARDS: Dict[str, List[Dict[str, Any]]] = {
    "CS1002": [  # Programming Fundamentals
        {"front": "What is a variable in programming?", "back": "A named storage location that holds a value and can be changed during program execution. Variables allow programs to store and manipulate data dynamically.", "difficulty": "easy", "tags": ["programming", "basics", "variables"]},
        {"front": "What is the difference between a compiler and an interpreter?", "back": "A compiler translates entire source code to machine code before execution, while an interpreter translates and executes code line by line. Compiled code runs faster, interpreted code is more flexible.", "difficulty": "medium", "tags": ["programming", "compilation", "interpretation"]},
        {"front": "What are the three basic control structures in programming?", "back": "Sequence (sequential execution), Selection (if/else statements for decision making), and Iteration (loops for repetition). These form the foundation of all program logic.", "difficulty": "easy", "tags": ["programming", "control-structures", "basics"]},
        {"front": "What is a function in programming?", "back": "A reusable block of code that performs a specific task and can be called with parameters. Functions promote code reusability, modularity, and make programs easier to maintain.", "difficulty": "easy", "tags": ["programming", "functions", "modularity"]},
        {"front": "What is the difference between pass by value and pass by reference?", "back": "Pass by value creates a copy of the variable, while pass by reference passes the memory address allowing modification of the original. Pass by value protects original data, pass by reference allows direct modification.", "difficulty": "medium", "tags": ["programming", "parameters", "memory"]},
        {"front": "What is a data type?", "back": "A classification that specifies which type of value a variable can hold (e.g., integer, string, boolean, float). Data types determine what operations can be performed on the variable.", "difficulty": "easy", "tags": ["programming", "data-types", "basics"]},
        {"front": "What is an array?", "back": "A collection of elements of the same data type stored in contiguous memory locations. Arrays allow efficient storage and access of multiple related values using an index.", "difficulty": "easy", "tags": ["programming", "arrays", "data-structures"]},
        {"front": "What is recursion?", "back": "A programming technique where a function calls itself to solve a problem. Recursion breaks complex problems into smaller, similar subproblems until a base case is reached.", "difficulty": "hard", "tags": ["programming", "recursion", "algorithms"]},
    ],
    "CS1004": [  # Object Oriented Programming
        {"front": "What are the four pillars of Object-Oriented Programming?", "back": "Encapsulation (bundling data and methods), Inheritance (reusing code from parent classes), Polymorphism (same interface, different implementations), and Abstraction (hiding complexity). These principles guide OOP design.", "difficulty": "medium", "tags": ["oop", "principles", "concepts"]},
        {"front": "What is encapsulation?", "back": "The bundling of data and methods that operate on that data within a single unit (class), hiding internal details. Encapsulation protects data integrity and provides controlled access through methods.", "difficulty": "medium", "tags": ["oop", "encapsulation", "data-hiding"]},
        {"front": "What is inheritance in OOP?", "back": "A mechanism where a new class (child/derived) inherits properties and methods from an existing class (parent/base). Inheritance promotes code reusability and establishes 'is-a' relationships.", "difficulty": "medium", "tags": ["oop", "inheritance", "reusability"]},
        {"front": "What is polymorphism?", "back": "The ability of objects of different classes to respond to the same method call in different ways. Polymorphism allows one interface to represent multiple forms, enabling flexible and extensible code.", "difficulty": "hard", "tags": ["oop", "polymorphism", "flexibility"]},
        {"front": "What is the difference between a class and an object?", "back": "A class is a blueprint or template that defines attributes and methods, while an object is an instance of that class created in memory. Multiple objects can be created from one class.", "difficulty": "easy", "tags": ["oop", "class", "object", "basics"]},
        {"front": "What is a constructor?", "back": "A special method in a class that is automatically called when an object is created. Constructors initialize object attributes and set up the initial state of the object.", "difficulty": "easy", "tags": ["oop", "constructors", "initialization"]},
        {"front": "What is method overriding?", "back": "A feature where a child class provides a specific implementation of a method that is already defined in its parent class. The overridden method in the child class replaces the parent's version.", "difficulty": "medium", "tags": ["oop", "inheritance", "overriding"]},
        {"front": "What is the difference between public, private, and protected access modifiers?", "back": "Public members are accessible everywhere, private members are only accessible within the same class, and protected members are accessible within the class and its subclasses.", "difficulty": "medium", "tags": ["oop", "access-modifiers", "encapsulation"]},
    ],
    "CS1005": [  # Discrete Structures
        {"front": "What is a set in discrete mathematics?", "back": "A collection of distinct objects, considered as an object in its own right. Sets are fundamental building blocks in discrete mathematics and are used to represent collections of elements.", "difficulty": "easy", "tags": ["discrete-math", "sets", "basics"]},
        {"front": "What is a graph in discrete structures?", "back": "A collection of vertices (nodes) connected by edges (links). Graphs model relationships and connections, widely used in computer science for networks, social media, and algorithms.", "difficulty": "medium", "tags": ["discrete-math", "graphs", "data-structures"]},
        {"front": "What is mathematical induction?", "back": "A proof technique used to prove statements about natural numbers by showing the base case (prove for n=1) and the inductive step (if true for n, then true for n+1).", "difficulty": "hard", "tags": ["discrete-math", "proofs", "induction"]},
        {"front": "What is a proposition in logic?", "back": "A declarative statement that is either true or false, but not both. Propositions form the basis of logical reasoning and mathematical proofs.", "difficulty": "easy", "tags": ["discrete-math", "logic", "propositions"]},
        {"front": "What is a function in discrete mathematics?", "back": "A relation from a set of inputs to a set of outputs where each input maps to exactly one output. Functions are fundamental in mathematics and computer science.", "difficulty": "medium", "tags": ["discrete-math", "functions", "relations"]},
        {"front": "What is the difference between a permutation and a combination?", "back": "A permutation is an arrangement where order matters, while a combination is a selection where order does not matter. Permutations count arrangements, combinations count selections.", "difficulty": "medium", "tags": ["discrete-math", "combinatorics", "counting"]},
        {"front": "What is a tree in graph theory?", "back": "A connected acyclic graph. Trees have exactly n-1 edges for n vertices and are used to represent hierarchical structures like file systems and organizational charts.", "difficulty": "medium", "tags": ["discrete-math", "graphs", "trees"]},
    ],
    "CS2001": [  # Data Structures
        {"front": "What is the time complexity of accessing an element in an array?", "back": "O(1) - constant time, as arrays support direct indexing", "difficulty": "easy", "tags": ["data-structures", "arrays", "complexity"]},
        {"front": "What is the difference between a stack and a queue?", "back": "Stack is LIFO (Last In First Out), Queue is FIFO (First In First Out)", "difficulty": "easy", "tags": ["data-structures", "stack", "queue"]},
        {"front": "What is a binary tree?", "back": "A tree data structure where each node has at most two children, referred to as left and right", "difficulty": "medium", "tags": ["data-structures", "trees", "binary-tree"]},
        {"front": "What is the time complexity of binary search?", "back": "O(log n) - logarithmic time complexity", "difficulty": "medium", "tags": ["data-structures", "algorithms", "search", "complexity"]},
        {"front": "What is a hash table?", "back": "A data structure that maps keys to values using a hash function to compute an index", "difficulty": "medium", "tags": ["data-structures", "hashing", "tables"]},
    ],
    "CS2005": [  # Database Systems
        {"front": "What is a primary key in a database?", "back": "A unique identifier for each record in a table that cannot be null. Primary keys ensure each row is uniquely identifiable and are used to establish relationships between tables.", "difficulty": "easy", "tags": ["database", "keys", "constraints"]},
        {"front": "What is normalization in database design?", "back": "The process of organizing data to reduce redundancy and improve data integrity. Normalization eliminates data duplication and ensures data consistency across the database.", "difficulty": "medium", "tags": ["database", "normalization", "design"]},
        {"front": "What is SQL?", "back": "Structured Query Language - a programming language used to manage and manipulate relational databases. SQL allows users to create, read, update, and delete data in databases.", "difficulty": "easy", "tags": ["database", "sql", "query-language"]},
        {"front": "What is ACID in database transactions?", "back": "Atomicity (all or nothing), Consistency (data remains valid), Isolation (concurrent transactions don't interfere), Durability (committed changes persist). ACID ensures reliable database transactions.", "difficulty": "hard", "tags": ["database", "transactions", "acid"]},
        {"front": "What is a foreign key?", "back": "A field in one table that references the primary key of another table, establishing a relationship. Foreign keys maintain referential integrity and enforce relationships between tables.", "difficulty": "medium", "tags": ["database", "keys", "relationships"]},
        {"front": "What is a database index?", "back": "A data structure that improves the speed of data retrieval operations. Indexes are created on columns frequently used in WHERE clauses, significantly speeding up queries.", "difficulty": "medium", "tags": ["database", "indexes", "performance"]},
        {"front": "What is the difference between DELETE and TRUNCATE?", "back": "DELETE removes specific rows and can be rolled back, while TRUNCATE removes all rows from a table and cannot be rolled back. TRUNCATE is faster but less flexible.", "difficulty": "medium", "tags": ["database", "sql", "operations"]},
        {"front": "What is a database view?", "back": "A virtual table based on the result of a SQL query. Views don't store data themselves but provide a way to present data from one or more tables in a specific format.", "difficulty": "medium", "tags": ["database", "views", "queries"]},
    ],
    "CS2006": [  # Operating Systems
        {"front": "What is an operating system?", "back": "System software that manages computer hardware, software resources, and provides services for computer programs. The OS acts as an intermediary between users and hardware.", "difficulty": "easy", "tags": ["operating-systems", "basics", "system-software"]},
        {"front": "What is a process in an operating system?", "back": "An instance of a program in execution, with its own memory space and resources. Processes are isolated from each other and managed by the OS scheduler.", "difficulty": "medium", "tags": ["operating-systems", "processes", "multitasking"]},
        {"front": "What is virtual memory?", "back": "A memory management technique that uses secondary storage to extend available RAM. Virtual memory allows programs to use more memory than physically available by swapping pages to disk.", "difficulty": "medium", "tags": ["operating-systems", "memory", "virtual-memory"]},
        {"front": "What is a deadlock?", "back": "A situation where two or more processes are blocked forever, waiting for each other to release resources. Deadlocks occur when processes hold resources and wait for others in a circular dependency.", "difficulty": "hard", "tags": ["operating-systems", "deadlock", "synchronization"]},
        {"front": "What is the difference between a process and a thread?", "back": "A process has its own memory space and is independent, while threads share memory within the same process. Threads are lighter weight and enable concurrent execution within a process.", "difficulty": "medium", "tags": ["operating-systems", "processes", "threads"]},
        {"front": "What is CPU scheduling?", "back": "The process of selecting which process should run on the CPU at a given time. Scheduling algorithms (FCFS, Round Robin, Priority) determine process execution order.", "difficulty": "medium", "tags": ["operating-systems", "scheduling", "cpu"]},
        {"front": "What is paging?", "back": "A memory management scheme where physical memory is divided into fixed-size blocks called pages. Paging allows non-contiguous allocation of memory to processes.", "difficulty": "hard", "tags": ["operating-systems", "memory", "paging"]},
        {"front": "What is a semaphore?", "back": "A synchronization primitive used to control access to shared resources. Semaphores use a counter to track available resources and prevent race conditions.", "difficulty": "hard", "tags": ["operating-systems", "synchronization", "semaphores"]},
    ],
    "CS2009": [  # Design and Analysis of Algorithms
        {"front": "What is Big O notation?", "back": "A mathematical notation describing the limiting behavior of a function, used to describe algorithm time/space complexity. Big O describes the worst-case scenario for algorithm performance.", "difficulty": "medium", "tags": ["algorithms", "complexity", "big-o"]},
        {"front": "What is the time complexity of merge sort?", "back": "O(n log n) - linearithmic time complexity. Merge sort divides the array in half recursively and then merges sorted halves, guaranteeing O(n log n) performance.", "difficulty": "medium", "tags": ["algorithms", "sorting", "complexity"]},
        {"front": "What is dynamic programming?", "back": "A method for solving complex problems by breaking them down into simpler subproblems and storing results to avoid recomputation. DP optimizes overlapping subproblems.", "difficulty": "hard", "tags": ["algorithms", "dynamic-programming", "optimization"]},
        {"front": "What is a greedy algorithm?", "back": "An algorithm that makes locally optimal choices at each step, hoping to find a global optimum. Greedy algorithms are efficient but don't always produce optimal solutions.", "difficulty": "medium", "tags": ["algorithms", "greedy", "optimization"]},
        {"front": "What is the difference between time complexity and space complexity?", "back": "Time complexity measures how runtime grows with input size, space complexity measures how memory usage grows. Both are expressed using Big O notation.", "difficulty": "easy", "tags": ["algorithms", "complexity", "analysis"]},
        {"front": "What is divide and conquer?", "back": "An algorithm design paradigm that divides a problem into smaller subproblems, solves them recursively, and combines solutions. Examples include merge sort and quicksort.", "difficulty": "medium", "tags": ["algorithms", "divide-conquer", "design"]},
        {"front": "What is backtracking?", "back": "A problem-solving technique that builds solutions incrementally and abandons partial solutions that cannot lead to valid solutions. Used in constraint satisfaction problems.", "difficulty": "hard", "tags": ["algorithms", "backtracking", "search"]},
        {"front": "What is the time complexity of quicksort?", "back": "Average case: O(n log n), Worst case: O(n²). Quicksort's performance depends on pivot selection, with average case being very efficient.", "difficulty": "medium", "tags": ["algorithms", "sorting", "complexity"]},
    ],
    "CS3001": [  # Computer Networks
        {"front": "What is the OSI model?", "back": "Open Systems Interconnection model - a 7-layer framework for network communication: Physical, Data Link, Network, Transport, Session, Presentation, Application. Each layer has specific functions.", "difficulty": "medium", "tags": ["networks", "osi", "protocols"]},
        {"front": "What is TCP/IP?", "back": "Transmission Control Protocol/Internet Protocol - the suite of communication protocols used on the Internet. TCP/IP is the foundation of modern networking and has 4 layers.", "difficulty": "medium", "tags": ["networks", "tcp-ip", "protocols"]},
        {"front": "What is the difference between TCP and UDP?", "back": "TCP is connection-oriented, reliable, and ensures ordered delivery. UDP is connectionless, faster, but unreliable with no delivery guarantees. TCP is for reliability, UDP for speed.", "difficulty": "medium", "tags": ["networks", "tcp", "udp", "protocols"]},
        {"front": "What is an IP address?", "back": "A unique numerical identifier assigned to each device on a network using IP protocol. IPv4 uses 32-bit addresses, IPv6 uses 128-bit addresses for more address space.", "difficulty": "easy", "tags": ["networks", "ip", "addressing"]},
        {"front": "What is DNS?", "back": "Domain Name System - translates human-readable domain names (like google.com) to IP addresses. DNS is essential for internet navigation and uses a hierarchical distributed database.", "difficulty": "easy", "tags": ["networks", "dns", "naming"]},
        {"front": "What is HTTP?", "back": "Hypertext Transfer Protocol - the protocol used for transferring web pages on the internet. HTTP defines how messages are formatted and transmitted between web browsers and servers.", "difficulty": "easy", "tags": ["networks", "http", "web", "protocols"]},
        {"front": "What is a router?", "back": "A network device that forwards data packets between computer networks. Routers use routing tables to determine the best path for data transmission across networks.", "difficulty": "medium", "tags": ["networks", "routing", "hardware"]},
        {"front": "What is a subnet mask?", "back": "A 32-bit number that divides an IP address into network and host portions. Subnet masks determine which part of an IP address identifies the network and which identifies the host.", "difficulty": "hard", "tags": ["networks", "subnetting", "addressing"]},
    ],
    "SE1001": [  # Introduction to Software Engineering
        {"front": "What is software engineering?", "back": "The application of engineering principles to the design, development, and maintenance of software. Software engineering applies systematic, disciplined approaches to software creation.", "difficulty": "easy", "tags": ["software-engineering", "basics", "definition"]},
        {"front": "What is the Software Development Life Cycle (SDLC)?", "back": "A process for planning, creating, testing, and deploying software applications. SDLC provides a structured approach to software development from conception to retirement.", "difficulty": "medium", "tags": ["software-engineering", "sdlc", "process"]},
        {"front": "What are the main phases of SDLC?", "back": "Requirements gathering and analysis, System design, Implementation/coding, Testing, Deployment, and Maintenance. Each phase has specific deliverables and goals.", "difficulty": "medium", "tags": ["software-engineering", "sdlc", "phases"]},
        {"front": "What is Agile methodology?", "back": "An iterative and incremental approach to software development that emphasizes collaboration, customer feedback, and rapid response to change. Agile values working software over documentation.", "difficulty": "medium", "tags": ["software-engineering", "agile", "methodology"]},
        {"front": "What is version control?", "back": "A system that tracks changes to files over time, allowing multiple developers to work on the same codebase. Git is the most popular version control system.", "difficulty": "easy", "tags": ["software-engineering", "version-control", "git"]},
        {"front": "What is software testing?", "back": "The process of evaluating software to verify it meets requirements and works correctly. Testing includes unit tests, integration tests, and system tests to ensure quality.", "difficulty": "easy", "tags": ["software-engineering", "testing", "quality"]},
        {"front": "What is code refactoring?", "back": "The process of restructuring existing code without changing its external behavior. Refactoring improves code readability, maintainability, and reduces technical debt.", "difficulty": "medium", "tags": ["software-engineering", "refactoring", "code-quality"]},
    ],
    "SE2001": [  # Software Requirements Engineering
        {"front": "What is a software requirement?", "back": "A description of what a system should do, its constraints, and quality attributes. Requirements define the capabilities and characteristics the software must possess.", "difficulty": "easy", "tags": ["requirements", "software-engineering", "specifications"]},
        {"front": "What is the difference between functional and non-functional requirements?", "back": "Functional requirements describe what the system does (features and behaviors), non-functional describe how well it performs (performance, security, usability).", "difficulty": "medium", "tags": ["requirements", "functional", "non-functional"]},
        {"front": "What is a use case?", "back": "A description of how a user interacts with a system to achieve a specific goal. Use cases capture system behavior from the user's perspective and help identify requirements.", "difficulty": "medium", "tags": ["requirements", "use-cases", "modeling"]},
        {"front": "What is requirements elicitation?", "back": "The process of gathering requirements from stakeholders through interviews, surveys, observation, and workshops. Elicitation is the first step in requirements engineering.", "difficulty": "medium", "tags": ["requirements", "elicitation", "gathering"]},
        {"front": "What is a requirements specification document?", "back": "A formal document that describes system requirements in detail. It serves as a contract between stakeholders and developers, guiding design and testing.", "difficulty": "medium", "tags": ["requirements", "documentation", "specifications"]},
        {"front": "What is requirements validation?", "back": "The process of checking that requirements are correct, complete, consistent, and achievable. Validation ensures requirements accurately represent stakeholder needs.", "difficulty": "medium", "tags": ["requirements", "validation", "quality"]},
        {"front": "What is traceability in requirements?", "back": "The ability to track requirements from their origin through design, implementation, and testing. Traceability helps ensure all requirements are addressed and tested.", "difficulty": "hard", "tags": ["requirements", "traceability", "management"]},
    ],
    "SE2002": [  # Software Design and Architecture
        {"front": "What is software architecture?", "back": "The high-level structure of a software system, defining components and their relationships. Architecture provides the blueprint for system design and guides implementation decisions.", "difficulty": "medium", "tags": ["architecture", "design", "structure"]},
        {"front": "What is design patterns?", "back": "Reusable solutions to commonly occurring problems in software design. Design patterns provide proven approaches to solving recurring design problems (e.g., Singleton, Factory, Observer).", "difficulty": "medium", "tags": ["design", "patterns", "reusability"]},
        {"front": "What is MVC architecture?", "back": "Model-View-Controller - a design pattern separating data (Model), UI (View), and logic (Controller). MVC promotes separation of concerns and makes applications more maintainable.", "difficulty": "medium", "tags": ["architecture", "mvc", "patterns"]},
        {"front": "What is the difference between high-level and low-level design?", "back": "High-level design focuses on system architecture, major components, and their interactions. Low-level design details specific modules, classes, and algorithms within components.", "difficulty": "medium", "tags": ["design", "architecture", "levels"]},
        {"front": "What is coupling and cohesion?", "back": "Coupling measures interdependence between modules (low is better), cohesion measures how well elements within a module work together (high is better). Good design has low coupling and high cohesion.", "difficulty": "hard", "tags": ["design", "coupling", "cohesion"]},
        {"front": "What is a microservices architecture?", "back": "An architectural style where applications are built as a collection of small, independent services. Each service runs in its own process and communicates via APIs.", "difficulty": "hard", "tags": ["architecture", "microservices", "distributed"]},
        {"front": "What is the SOLID principles?", "back": "Five object-oriented design principles: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion. SOLID promotes maintainable, flexible code.", "difficulty": "hard", "tags": ["design", "solid", "principles", "oop"]},
    ],
    "AI2002": [  # Artificial Intelligence
        {"front": "What is artificial intelligence?", "back": "The simulation of human intelligence in machines programmed to think and learn like humans. AI encompasses machine learning, natural language processing, computer vision, and robotics.", "difficulty": "easy", "tags": ["ai", "basics", "definition"]},
        {"front": "What is machine learning?", "back": "A subset of AI that enables systems to learn and improve from experience without explicit programming. ML algorithms build models from training data to make predictions.", "difficulty": "medium", "tags": ["ai", "machine-learning", "learning"]},
        {"front": "What is the difference between supervised and unsupervised learning?", "back": "Supervised learning uses labeled data to train models (classification, regression). Unsupervised learning finds patterns in unlabeled data (clustering, dimensionality reduction).", "difficulty": "medium", "tags": ["ai", "machine-learning", "types"]},
        {"front": "What is a neural network?", "back": "A computing system inspired by biological neural networks, consisting of interconnected nodes (neurons) organized in layers. Neural networks can learn complex patterns from data.", "difficulty": "hard", "tags": ["ai", "neural-networks", "deep-learning"]},
        {"front": "What is deep learning?", "back": "A subset of machine learning using neural networks with multiple hidden layers. Deep learning excels at processing large amounts of data and recognizing complex patterns.", "difficulty": "hard", "tags": ["ai", "deep-learning", "neural-networks"]},
        {"front": "What is overfitting in machine learning?", "back": "When a model learns training data too well, including noise and outliers, resulting in poor performance on new data. Overfitting occurs when the model is too complex.", "difficulty": "medium", "tags": ["ai", "machine-learning", "overfitting"]},
        {"front": "What is reinforcement learning?", "back": "A type of machine learning where an agent learns to make decisions by interacting with an environment and receiving rewards or penalties. The agent learns optimal strategies through trial and error.", "difficulty": "hard", "tags": ["ai", "reinforcement-learning", "agents"]},
    ],
    "CS3002": [  # Information Security
        {"front": "What is cryptography?", "back": "The practice of secure communication in the presence of adversaries. Cryptography uses mathematical algorithms to encrypt and decrypt data, ensuring confidentiality and integrity.", "difficulty": "medium", "tags": ["security", "cryptography", "encryption"]},
        {"front": "What is the difference between symmetric and asymmetric encryption?", "back": "Symmetric encryption uses one shared key for both encryption and decryption (faster). Asymmetric encryption uses a public-private key pair (more secure, slower).", "difficulty": "medium", "tags": ["security", "encryption", "keys"]},
        {"front": "What is a firewall?", "back": "A network security device that monitors and filters incoming/outgoing network traffic based on security rules. Firewalls act as barriers between trusted and untrusted networks.", "difficulty": "easy", "tags": ["security", "firewall", "networks"]},
        {"front": "What is SQL injection?", "back": "A code injection technique that exploits security vulnerabilities in database queries by inserting malicious SQL code. SQL injection can lead to data theft or database manipulation.", "difficulty": "hard", "tags": ["security", "vulnerabilities", "databases"]},
        {"front": "What is authentication vs authorization?", "back": "Authentication verifies who you are (login credentials), authorization determines what you can access (permissions). Authentication comes first, then authorization.", "difficulty": "easy", "tags": ["security", "authentication", "authorization"]},
        {"front": "What is a hash function?", "back": "A one-way mathematical function that converts input data into a fixed-size string. Hash functions are used for password storage, data integrity verification, and digital signatures.", "difficulty": "medium", "tags": ["security", "hashing", "cryptography"]},
        {"front": "What is a DDoS attack?", "back": "Distributed Denial of Service attack - overwhelming a server with traffic from multiple sources to make it unavailable. DDoS attacks flood systems with requests beyond their capacity.", "difficulty": "medium", "tags": ["security", "ddos", "attacks"]},
    ],
    "MT1003": [  # Calculus and Analytical Geometry
        {"front": "What is a derivative?", "back": "The rate of change of a function with respect to a variable, representing the slope of the tangent line. Derivatives measure instantaneous rates of change and are fundamental in calculus.", "difficulty": "medium", "tags": ["calculus", "derivatives", "mathematics"]},
        {"front": "What is an integral?", "back": "The reverse process of differentiation, representing the area under a curve. Integrals calculate accumulation and are used to find areas, volumes, and solve differential equations.", "difficulty": "medium", "tags": ["calculus", "integrals", "mathematics"]},
        {"front": "What is the chain rule?", "back": "A formula for computing the derivative of a composition of functions. If y = f(g(x)), then dy/dx = f'(g(x)) * g'(x). The chain rule is essential for differentiating composite functions.", "difficulty": "hard", "tags": ["calculus", "derivatives", "rules"]},
        {"front": "What is the product rule?", "back": "A rule for differentiating products of functions. If y = f(x) * g(x), then y' = f'(x) * g(x) + f(x) * g'(x). The product rule is used when multiplying two functions.", "difficulty": "medium", "tags": ["calculus", "derivatives", "rules"]},
        {"front": "What is the quotient rule?", "back": "A rule for differentiating quotients of functions. If y = f(x)/g(x), then y' = (f'(x) * g(x) - f(x) * g'(x)) / [g(x)]². Used when dividing two functions.", "difficulty": "medium", "tags": ["calculus", "derivatives", "rules"]},
        {"front": "What is a limit?", "back": "The value that a function approaches as the input approaches a certain value. Limits are fundamental to calculus and define both derivatives and integrals.", "difficulty": "medium", "tags": ["calculus", "limits", "mathematics"]},
        {"front": "What is continuity?", "back": "A function is continuous at a point if the limit exists, the function is defined, and the limit equals the function value. Continuity ensures smooth, unbroken graphs.", "difficulty": "medium", "tags": ["calculus", "continuity", "functions"]},
    ],
    "MT1004": [  # Linear Algebra
        {"front": "What is a matrix?", "back": "A rectangular array of numbers, symbols, or expressions arranged in rows and columns. Matrices are used to represent linear transformations and solve systems of equations.", "difficulty": "easy", "tags": ["linear-algebra", "matrices", "basics"]},
        {"front": "What is a vector?", "back": "A quantity having both magnitude and direction, represented as an ordered list of numbers. Vectors can represent points, directions, or physical quantities in space.", "difficulty": "easy", "tags": ["linear-algebra", "vectors", "basics"]},
        {"front": "What is matrix multiplication?", "back": "A binary operation that produces a matrix from two matrices, following specific rules. Matrix multiplication is not commutative (AB ≠ BA) and requires compatible dimensions.", "difficulty": "medium", "tags": ["linear-algebra", "matrices", "operations"]},
        {"front": "What is the determinant of a matrix?", "back": "A scalar value that can be computed from a square matrix. The determinant indicates whether a matrix is invertible and relates to the volume scaling factor of linear transformations.", "difficulty": "hard", "tags": ["linear-algebra", "matrices", "determinants"]},
        {"front": "What is an inverse matrix?", "back": "A matrix that when multiplied by the original matrix yields the identity matrix. Only square matrices with non-zero determinants have inverses.", "difficulty": "hard", "tags": ["linear-algebra", "matrices", "inverse"]},
        {"front": "What is a linear transformation?", "back": "A function between vector spaces that preserves vector addition and scalar multiplication. Linear transformations can be represented by matrices.", "difficulty": "hard", "tags": ["linear-algebra", "transformations", "functions"]},
        {"front": "What is the dot product?", "back": "An operation that takes two vectors and returns a scalar. The dot product measures the angle between vectors and is used in projections and calculations.", "difficulty": "medium", "tags": ["linear-algebra", "vectors", "operations"]},
    ],
    "EE1005": [  # Digital Logic Design
        {"front": "What is a logic gate?", "back": "An electronic circuit that performs a logical operation on one or more binary inputs. Logic gates are the fundamental building blocks of digital circuits.", "difficulty": "easy", "tags": ["digital-logic", "gates", "circuits"]},
        {"front": "What are the basic logic gates?", "back": "AND (both inputs true), OR (at least one true), NOT (inversion), NAND (NOT AND), NOR (NOT OR), XOR (exclusive OR), XNOR (exclusive NOR). These form all digital logic.", "difficulty": "easy", "tags": ["digital-logic", "gates", "basics"]},
        {"front": "What is a flip-flop?", "back": "A circuit that stores one bit of information, used as a basic memory element. Flip-flops are bistable devices that can maintain state, essential for sequential circuits.", "difficulty": "medium", "tags": ["digital-logic", "flip-flops", "memory"]},
        {"front": "What is the difference between combinational and sequential circuits?", "back": "Combinational circuits output depends only on current inputs. Sequential circuits have memory and output depends on current inputs and previous state. Sequential circuits use flip-flops.", "difficulty": "medium", "tags": ["digital-logic", "circuits", "types"]},
        {"front": "What is a truth table?", "back": "A table showing all possible input combinations and their corresponding outputs for a logic function. Truth tables completely describe the behavior of logic circuits.", "difficulty": "easy", "tags": ["digital-logic", "truth-tables", "analysis"]},
        {"front": "What is Boolean algebra?", "back": "A branch of algebra dealing with binary variables and logical operations. Boolean algebra uses AND, OR, and NOT operations to simplify and analyze digital circuits.", "difficulty": "medium", "tags": ["digital-logic", "boolean-algebra", "mathematics"]},
        {"front": "What is a multiplexer?", "back": "A combinational circuit that selects one of several input signals and forwards it to a single output. Multiplexers use select lines to choose which input to pass through.", "difficulty": "medium", "tags": ["digital-logic", "multiplexers", "circuits"]},
    ],
    "EE2003": [  # Computer Organization and Assembly Language
        {"front": "What is assembly language?", "back": "A low-level programming language that corresponds closely to machine code instructions. Assembly provides direct control over hardware and is one step above machine code.", "difficulty": "medium", "tags": ["assembly", "low-level", "programming"]},
        {"front": "What is a CPU?", "back": "Central Processing Unit - the primary component that executes instructions and processes data. The CPU consists of ALU, control unit, and registers, and is the brain of the computer.", "difficulty": "easy", "tags": ["computer-organization", "cpu", "hardware"]},
        {"front": "What is the difference between RAM and ROM?", "back": "RAM (Random Access Memory) is volatile, read-write memory for temporary data. ROM (Read-Only Memory) is non-volatile, read-only memory for permanent data like BIOS.", "difficulty": "easy", "tags": ["computer-organization", "memory", "storage"]},
        {"front": "What is the instruction cycle?", "back": "The sequence of steps a CPU follows to execute an instruction: Fetch (get instruction), Decode (interpret instruction), Execute (perform operation), Store (save results).", "difficulty": "medium", "tags": ["computer-organization", "cpu", "instructions"]},
        {"front": "What is a register?", "back": "A small, high-speed storage location within the CPU used to hold data, addresses, or instructions. Registers are the fastest type of memory and are directly accessible to the CPU.", "difficulty": "easy", "tags": ["computer-organization", "registers", "cpu"]},
        {"front": "What is the difference between RISC and CISC architectures?", "back": "RISC (Reduced Instruction Set Computer) uses simple, fixed-length instructions. CISC (Complex Instruction Set Computer) uses complex, variable-length instructions. RISC is faster, CISC is more compact.", "difficulty": "hard", "tags": ["computer-organization", "architecture", "risc", "cisc"]},
        {"front": "What is cache memory?", "back": "A small, fast memory located between CPU and main memory that stores frequently accessed data. Cache reduces memory access time and improves overall system performance.", "difficulty": "medium", "tags": ["computer-organization", "cache", "memory"]},
    ],
}


def get_flashcards_for_courses(course_codes: List[str]) -> List[Dict[str, Any]]:
    """Get flashcards for a list of course codes."""
    flashcards = []
    for course_code in course_codes:
        if course_code in COURSE_FLASHCARDS:
            flashcards.extend(COURSE_FLASHCARDS[course_code])
    return flashcards


def get_all_course_codes() -> List[str]:
    """Get all available course codes."""
    return list(COURSE_FLASHCARDS.keys())

